# Generated by Django 5.0.1 on 2024-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('foods', 'Foods'), ('drinks', 'Drinks'), ('accessories', 'Accessories')], default='------', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'Products Table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('role', models.IntegerField(choices=[(5059, 'Admin'), (4316, 'User')], default=4316, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Users Table',
            },
        ),
    ]
